__all__ = ["SYNTHETIC_DATASET", "SYNTHETIC_DISTANCE_DATASET", "SYNTHETIC_IMBALANCED_DATASET",
           "SYNTHETIC_DISTANCE_IMBALANCED_DATASET", "OPENML_DATASET", "MULTI_LAYER_PERCEPTRON", "SGD_CLASSIFIER",
           "RIDGE_CLASSIFIER", "LINEAR_SVC", "DECISION_TREE", "EXTRA_TREE", "RANDOM_FOREST", "EXTRA_TREES",
           "ADA_BOOST_CLASSIFIER", "GRADIENT_BOOSTING_CLASSIFICATION", "CLASSIFICATION", "BAYES_PREDICTOR",
           "MAJORITY_VOTING", "RANDOM_CLASSIFIER", "MUTUAL_INFORMATION", "MUTUAL_INFORMATION_NEW", "INFORMEDNESS",
           "MCC", "AUC_SCORE", "ACCURACY", "F_SCORE", "CONFUSION_MATRIX", "FPR", "FNR", "SANTHIUB", "HELLMANUB",
           "FANOSLB", "FANOS_ADJUSTEDLB", "ESTIMATED_MUTUAL_INFORMATION", "ESTIMATED_MUTUAL_INFORMATION_SCORE",
           "AUTO_SKLEARN", "TABPFN", "TABPFN_VAR", "AUTO_GLUON", "AUTO_GLUON_STACK", "AUTO_ML", "LEAKAGE_DETECTION",
           "GMM_MI_ESTIMATOR", "MINE_MI_ESTIMATOR", "MID_POINT_MI_ESTIMATION", "LOG_LOSS_MI_ESTIMATION",
           "PC_SOFTMAX_MI_ESTIMATION", "MCMC_MI_ESTIMATION", "MCMC_LOG_LOSS", "MCMC_PC_SOFTMAX", "MCMC_SOFTMAX",
           "LEAKAGE_DETECTION_NEW", "LOG_LOSS_MI_ESTIMATION_ISOTONIC_REGRESSION", "OPENML_PADDING_DATASET",
           "LOG_LOSS_MI_ESTIMATION_PLATT_SCALING", "LOG_LOSS_MI_ESTIMATION_BETA_CALIBRATION",
           "LOG_LOSS_MI_ESTIMATION_HISTOGRAM_BINNING", "LOG_LOSS_MI_ESTIMATION_TEMPERATURE_SCALING",
           "PC_SOFTMAX_MI_ESTIMATION_ISOTONIC_REGRESSION", "PC_SOFTMAX_MI_ESTIMATION_PLATT_SCALING",
           "PC_SOFTMAX_MI_ESTIMATION_BETA_CALIBRATION", "PC_SOFTMAX_MI_ESTIMATION_HISTOGRAM_BINNING",
           "PC_SOFTMAX_MI_ESTIMATION_TEMPERATURE_SCALING", "ISOTONIC_REGRESSION", "PLATT_SCALING", "HISTOGRAM_BINNING",
           "BETA_CALIBRATION", "TEMPERATURE_SCALING", "PAIRED_TTEST", "FISHER_EXACT_TEST_MEAN",
           "FISHER_EXACT_TEST_MEDIAN", "LOGS_FOLDER", "RESULT_FOLDER", "EXPERIMENTS", "OPTIMIZER_FOLDER",
           "MINE_MI_ESTIMATOR_HPO", "PAIRED_TTEST_RANDOM", "LEAKAGE_DETECTION_PADDING"]
LOGS_FOLDER = "logs"
RESULT_FOLDER = "results"
EXPERIMENTS = "experiments"
OPTIMIZER_FOLDER = "optimizers"

SYNTHETIC_DATASET = "synthetic"
SYNTHETIC_IMBALANCED_DATASET = "synthetic_imbalanced"
SYNTHETIC_DISTANCE_DATASET = "synthetic_distance"
SYNTHETIC_DISTANCE_IMBALANCED_DATASET = "synthetic_distance_imbalanced"
OPENML_DATASET = "openml_dataset"
OPENML_PADDING_DATASET = "openml_padding_dataset"

MULTI_LAYER_PERCEPTRON = "mlp"
SGD_CLASSIFIER = "sgd_classifier"
RIDGE_CLASSIFIER = "ridge_classifier"
LINEAR_SVC = "svm"
DECISION_TREE = "decision_tree"
EXTRA_TREE = "extra_tree"
RANDOM_FOREST = "random_forest"
EXTRA_TREES = "extra_trees"
ADA_BOOST_CLASSIFIER = "adaboost"
GRADIENT_BOOSTING_CLASSIFICATION = "gradient_boosting"
BAYES_PREDICTOR = "bayes_predictor"
MAJORITY_VOTING = "majority_voting"

AUTO_SKLEARN = "auto_sklearn"
AUTO_GLUON = "auto_gluon"
AUTO_GLUON_STACK = "auto_gluon_stack"
TABPFN_VAR = "tab_pfn_var"
TABPFN = "tab_pfn"
GMM_MI_ESTIMATOR = "gmm_mi_estimator"
MINE_MI_ESTIMATOR = "mine_mi_estimator"
MINE_MI_ESTIMATOR_HPO = "mine_mi_estimator_hpo"

MUTUAL_INFORMATION = "mutual_information"
MUTUAL_INFORMATION_NEW = "mutual_information_new"
CLASSIFICATION = "classification"
AUTO_ML = "automl"
LEAKAGE_DETECTION = "leakage_detection"
LEAKAGE_DETECTION_NEW = "leakage_detection_new"
LEAKAGE_DETECTION_PADDING = "leakage_detection_padding"

INFORMEDNESS = "BalancedAccuracy"
MCC = "MathewsCorrelationCoefficient"
AUC_SCORE = "AucScore"
CONFUSION_MATRIX = "ConfusionMatrix"
F_SCORE = "F1Score"
ACCURACY = "Accuracy"
FPR = "FalsePositiveRate"
FNR = "FalseNegativeRate"
SANTHI = "SanthiVardy"
HELLMAN = "HellmanRaviv"
FANOS = "Fanos"
FANOS_ADJUSTED = "FanosAdjusted"
UPPER = "UpperBound"
LOWER = "LowerBound"
SANTHIUB = SANTHI + UPPER
HELLMANUB = HELLMAN + UPPER
FANOSLB = FANOS + LOWER
FANOS_ADJUSTEDLB = FANOS_ADJUSTED + LOWER

ESTIMATED_MUTUAL_INFORMATION = "EstimatedMutualInformation"
ESTIMATED_MUTUAL_INFORMATION_SCORE = "EstimatedMutualInformationScore"
MID_POINT_MI_ESTIMATION = "MidPointMI"
LOG_LOSS_MI_ESTIMATION = "LogLossMI"
PC_SOFTMAX_MI_ESTIMATION = "PCSoftmaxMI"
MCMC_MI_ESTIMATION = "MCMCBayesMI"
MCMC_LOG_LOSS = "MCMCLogLossBayesMI"
MCMC_PC_SOFTMAX = "MCMCPCSoftmaxBayesMI"
MCMC_SOFTMAX = "MCMCSoftmaxBayesMI"

ISOTONIC_REGRESSION = "IsotonicRegression"
PLATT_SCALING = "PlattScaling"
HISTOGRAM_BINNING = "HistogramBinning"
BETA_CALIBRATION = "BetaCalibration"
TEMPERATURE_SCALING = "TemperatureScaling"

LOG_LOSS_MI_ESTIMATION_ISOTONIC_REGRESSION = f"{LOG_LOSS_MI_ESTIMATION}{ISOTONIC_REGRESSION}"
LOG_LOSS_MI_ESTIMATION_PLATT_SCALING = f"{LOG_LOSS_MI_ESTIMATION}{PLATT_SCALING}"
LOG_LOSS_MI_ESTIMATION_BETA_CALIBRATION = f"{LOG_LOSS_MI_ESTIMATION}{BETA_CALIBRATION}"
LOG_LOSS_MI_ESTIMATION_HISTOGRAM_BINNING = f"{LOG_LOSS_MI_ESTIMATION}{HISTOGRAM_BINNING}"
LOG_LOSS_MI_ESTIMATION_TEMPERATURE_SCALING = f"{LOG_LOSS_MI_ESTIMATION}{TEMPERATURE_SCALING}"

PC_SOFTMAX_MI_ESTIMATION_ISOTONIC_REGRESSION = f"{PC_SOFTMAX_MI_ESTIMATION}{ISOTONIC_REGRESSION}"
PC_SOFTMAX_MI_ESTIMATION_PLATT_SCALING = f"{PC_SOFTMAX_MI_ESTIMATION}{PLATT_SCALING}"
PC_SOFTMAX_MI_ESTIMATION_BETA_CALIBRATION = f"{PC_SOFTMAX_MI_ESTIMATION}{BETA_CALIBRATION}"
PC_SOFTMAX_MI_ESTIMATION_HISTOGRAM_BINNING = f"{PC_SOFTMAX_MI_ESTIMATION}{HISTOGRAM_BINNING}"
PC_SOFTMAX_MI_ESTIMATION_TEMPERATURE_SCALING = f"{PC_SOFTMAX_MI_ESTIMATION}{TEMPERATURE_SCALING}"

PAIRED_TTEST = "paired-t-test"
PAIRED_TTEST_RANDOM = "paired-t-test-random"
FISHER_EXACT_TEST_MEAN = "fishers-exact-mean"
FISHER_EXACT_TEST_MEDIAN = "fishers-exact-median"
MAJORITY_VOTING = "majority_voting"
RANDOM_CLASSIFIER = "random_classifier"
