name: Build and Deploy Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "docs-deployment"
  cancel-in-progress: false

jobs:
  # Build and deploy Sphinx documentation
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.5"

    - name: Install dependencies for docs
      run: |
        export SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Debugging
      run: |
        pwd
        ls -la
        make help

    - name: Build Sphinx docs
      run: |
        cd docs
        make clean
        make html  # or make docs based on your Makefile
        sphinx-build -W -b html source _build/html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4